poetry/analytics/urls.py
from django.urls import path
from . import views

app_name = 'analytics'

urlpatterns = [
    path('options/<poet>/', views.checkbox_dictionary, name='analytics_main'),
    path('dictionary/<int:pk>/', views.poem_dictionary, name='pd'),
    path('all_words_counted/<poet>/', views.all_words_counted, name='all_words_counted'),
    path('top_100_nouns/<poet>/', views.top_100_nouns, name='top_100_nouns'),
    path('top_100_adjf/<poet>/', views.top_100_adjf, name='top_100_adjf'),
    path('top_100_nouns_and_adjf/<poet>/', views.top_100_nouns_and_adjf, name='top_100_nouns_and_adjf'),
    path('top_100_verbs/<poet>/', views.top_100_verbs, name='top_100_verbs'),
    path('top_100_nouns_and_verbs/<poet>/', views.top_100_nouns_and_verbs, name='top_100_nouns_and_verbs'),
    path('top_100_nouns_and_verbs_and_adjf/<poet>/', views.top_100_nouns_and_verbs_and_adjf, name='top_100_nouns_and_verbs_and_adjf'),
    path('top_100_verbs_and_adjf/<poet>/', views.top_100_verbs_and_adjf, name='top_100_verbs_and_adjf'),


]

poetry/poems/urls.py
from django.urls import path
from . import views


app_name = 'poems'

urlpatterns = [
    path('poet/<poet>', views.poems_author, name='poems_author'),
    path('contents/<poet>', views.contents_author, name='contents_author'),
    path('add/', views.poem_add, name='poem_add'),
    path('poem_single/<int:pk>/', views.PoemDetailView.as_view(), name='poem_single'),
    path('delete/<int:pk>/', views.PoemDeleteView.as_view(), name='poem_delete'),
    path('contents/', views.ContentsView.as_view(), name='contents'),
    path('audio/<int:pk>/', views.audio_poem, name='audio'),
    path('update/<int:pk>/', views.PoemUpdateView.as_view(), name='poem_update'),
]

poetry/poetry/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


from rest_framework import routers
from poems.api_views import TagViewSet, EmelyanovaPoemViewSet



# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register('tag', TagViewSet)
router.register('emelyanova', EmelyanovaPoemViewSet)








from users.models import CustomAuthToken


urlpatterns = [
    path('admin/', admin.site.urls),
    path('poems/', include('poems.urls')),
    path('users/', include('users.urls')),
    path('analytics/', include('analytics.urls')),
    path('', views.home_page, name ='home'),
    path('api/v0/', include(router.urls)),
    path('api_token/', CustomAuthToken.as_view())


]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
'''
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns
'''

# from rest_framework.authtoken import views
#
# urlpatterns += [
#     path('api_token/', views.obtain_auth_token)
# ]

poetry/analytics/models.py
from django.db import models



# Create your models here.
class DictionaryForm(models.Model):
    is_noun = models.BooleanField("Существительные", default=False)  # NOUN имя существительное хомяк
    is_adjf = models.BooleanField("Прилагательные", default=False) #ADJF имя прилагательное (полное) хороший + краткие прилагательные
    is_verb = models.BooleanField("Глаголы", default=False) #ADJF имя прилагательное (полное) хороший

'''
all_noun = []  # NOUN имя существительное хомяк
all_adjf = []  # ADJF имя прилагательное (полное) хороший
all_adjs = []  # ADJS имя прилагательное (краткое) хорош
all_comp = []  # COMP компаратив лучше, получше, выше
all_verb = []  # VERB глагол (личная форма) говорю, говорит, говорил
all_infn = []  # INFN глагол (инфинитив) говорить, сказать
all_prtf = []  # PRTF причастие (полное) прочитавший, прочитанная
all_prts = []  # PRTS причастие (краткое) прочитана
all_grnd = []  # GRND деепричастие прочитав, рассказывая
all_numr = []  # NUMR числительное три, пятьдесят
all_advb = []  # ADVB наречие круто
all_npro = []  # NPRO местоимение-существительное он
all_pred = []  # PRED предикатив некогда
all_prep = []  # PREP предлог в
all_conj = []  # CONJ союз и
all_prcl = []  # PRCL частица бы, же, лишь
all_intj = []  # INTJ междометие
unknown_part = []  # не определенные pymorphy2 части речи
'''

poetry/analytics/forms.py
from django import forms
from .models import DictionaryForm

class DictionaryFormPartOfSpeech(forms.ModelForm):


    class Meta:
        model = DictionaryForm
        fields = ('is_noun', 'is_adjf', 'is_verb')

poetry/analytics/views.py
from django.shortcuts import render,get_object_or_404
from django.shortcuts import render, HttpResponseRedirect, reverse
from poems.models import Poem, Poet
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
import collections, pymorphy2
from .PoetAnalytics import MetaPoet, words_counter, top_100
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .forms import DictionaryFormPartOfSpeech



# подсчет числа слов всего, уникальных слов, топ 100 слов
def all_words_counted(request, poet):
    poems = Poem.objects.filter(poet_name__last_name=poet) # все cтихи одного поэта
    poems_all, counter_all, counter_unique, result, results_list_words,  results_list_counts = words_counter(poems)
    return render(request, 'analytics/poet_analytics.html', {'poet':poet, 'poems_all':poems_all,'counter_all': counter_all,'counter_unique':counter_unique, 'result':result,'results_list_words':results_list_words, 'results_list_counts': results_list_counts})


def poem_dictionary(request, pk):
    poem_original = get_object_or_404(Poem, pk=pk)
    poem = str(poem_original.poem_text)
    meta_poem = MetaPoet(poem)  # создаем объект класса MetaPoet, куда передаем стихи
    meta_poem.remove_punctuation()
    meta_poem.split_words()
    meta_poem.lower_case()
    lemmed_words = meta_poem.lemma()  # список всех лемматизированных слов
    len_lemmed_words = len(lemmed_words)
    unique_words_list = meta_poem.unique_words()
    len_unique_words = len(unique_words_list)
    word_list_poem = meta_poem.poem_dictionary()
    return render(request, 'analytics/poem_dictionary.html', {'pk':pk, 'len_unique_words':len_unique_words,'len_lemmed_words':len_lemmed_words,'poem': word_list_poem, 'poem_original': poem_original})


def checkbox_dictionary(request, poet):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        form = DictionaryFormPartOfSpeech(request.POST)
        if form.is_valid():
            is_noun = form.cleaned_data['is_noun']
            is_adjf = form.cleaned_data['is_adjf']
            is_verb = form.cleaned_data['is_verb']

            # NOUN
            if is_noun==True and is_adjf==False and is_verb==False:
                return HttpResponseRedirect(reverse('analytics:top_100_nouns', args=(poet,)))
            # ADJF
            if is_noun==False and is_adjf==True and is_verb==False:
                return HttpResponseRedirect(reverse('analytics:top_100_adjf', args=(poet,)))
            #VERB
            if is_noun==False and is_adjf==False and is_verb==True:
                return HttpResponseRedirect(reverse('analytics:top_100_verbs', args=(poet,)))
            # NOUN AND ADJF
            if is_noun==True and is_adjf==True and is_verb==False:
                return HttpResponseRedirect(reverse('analytics:top_100_nouns_and_adjf', args=(poet,)))


            if is_noun == True and is_adjf == False and is_verb == True:
                return HttpResponseRedirect(reverse('analytics:top_100_nouns_and_verbs', args=(poet,)))
            if is_verb and is_noun==True and is_adjf==True:
                return HttpResponseRedirect(reverse('analytics:top_100_nouns_and_verbs_and_adjf', args=(poet,)))
            if is_verb and is_noun==False and is_adjf==True:
                return HttpResponseRedirect(reverse('analytics:top_100_verbs_and_adjf', args=(poet,)))
            else:
                return all_words_counted(request, poet)
    else:
        form = DictionaryFormPartOfSpeech()

        return render(request, 'analytics/checkbox.html', {'form': form, 'poet':poet})

# топ-100 по частям речи

def top_100_nouns(request, poet):
    poems = Poem.objects.filter(poet_name__last_name=poet) # все объекты класса Стихи
    poems_all, counter_all, counter_unique, all_lemmed_words = top_100(poems)
    result = all_lemmed_words.top_100_nouns()
    return render(request, 'analytics/top_100_nouns.html',
                      {'result': result, 'poems_all':poems_all,'counter_all': counter_all,'counter_unique':counter_unique})


def top_100_adjf(request, poet):
    poems = Poem.objects.filter(poet_name__last_name=poet)
    poems_all, counter_all, counter_unique, all_lemmed_words = top_100(poems)
    result = all_lemmed_words.top_100_adjf()
    return render(request, 'analytics/top_100_adjf.html',
                      {'result': result, 'poems_all':poems_all,'counter_all': counter_all,'counter_unique':counter_unique})

def top_100_nouns_and_adjf(request, poet):
    poems = Poem.objects.filter(poet_name__last_name=poet) # все объекты класса Стихи
    poems_all, counter_all, counter_unique, all_lemmed_words = top_100(poems)
    result = all_lemmed_words.top_100_nouns_and_adjf()
    return render(request, 'analytics/top_100_nouns_and_adjf.html',
                      {'result': result, 'poems_all':poems_all,'counter_all': counter_all,'counter_unique':counter_unique})


def top_100_verbs(request, poet):
    poems = Poem.objects.filter(poet_name__last_name=poet) # все объекты класса Стихи
    poems_all, counter_all, counter_unique, all_lemmed_words = top_100(poems)
    result = all_lemmed_words.top_100_verbs()
    return render(request, 'analytics/top_100_verbs.html',
                      {'result': result, 'poems_all':poems_all,'counter_all': counter_all,'counter_unique':counter_unique})

def top_100_nouns_and_verbs(request, poet):
    poems = Poem.objects.filter(poet_name__last_name=poet) # все объекты класса Стихи
    poems_all, counter_all, counter_unique, all_lemmed_words = top_100(poems)
    result = all_lemmed_words.top_100_nouns_and_verbs()
    return render(request, 'analytics/top_100_nouns_and_verbs.html',
                      {'result': result, 'poems_all':poems_all,'counter_all': counter_all,'counter_unique':counter_unique})

def top_100_nouns_and_verbs_and_adjf(request, poet):
    poems = Poem.objects.filter(poet_name__last_name=poet) # все объекты класса Стихи
    poems_all, counter_all, counter_unique, all_lemmed_words = top_100(poems)
    result = all_lemmed_words.top_100_nouns_and_verbs_and_adjf()
    return render(request, 'analytics/top_100_nouns_and_verbs_and_adjf.html',
                      {'result': result, 'poems_all':poems_all,'counter_all': counter_all,'counter_unique':counter_unique})

def top_100_verbs_and_adjf(request, poet):
    poems = Poem.objects.filter(poet_name__last_name=poet) # все объекты класса Стихи
    poems_all, counter_all, counter_unique, all_lemmed_words = top_100(poems)
    result = all_lemmed_words.top_100_verbs_and_adjf()
    return render(request, 'analytics/top_100_verbs_and_adjf.html', {'result': result, 'poems_all':poems_all,'counter_all': counter_all,'counter_unique':counter_unique})

poetry/analytics/templates/analytics/analytics_form.html
{% extends 'poems/base.html' %}
{% block content %}



<div class="container-1">
    <div class="block-main box-flex wow fadeInUp  data-wow-duration="2s">
        <h3 style="text-align: center"><a href="{% url 'poems:poem_single' pk=poem_original.pk %}">{{poem_original.poem_title}}</a></h3>
        <p class="text-poem">{{poem_original.poem_text}}</p>
     </div>
</div>

<div class="wow fadeIn data-wow-duration="2s"">
<p style="text-align: center; text-transform: uppercase">Словарь стихотворения</p>
</div>

<div class="container-numbers">

    <div>
        <p>Всего слов</p>
        <p><input id="len_lemmed_words" value="0"></p>
    </div>
    <div>
        <p>Уникальных слов</p>
        <p><input id="len_unique_words" value="0"></p>
    </div>

</div>

    <div class="container-dict">
        {% for p, j in poem.items %}
            <div class="wow fadeInLeft  data-wow-duration="2s"">
                <p style="background-color: rgba(0, 128, 128, 0.4); color: white">{{p}}</p>
                {% for word in j %}
                {{word}}
                {% endfor %}
             </div>
        {% endfor %}
    </div>

<p><a href="{% url 'poems:poems' %}">К стихотворениям</a></p>
{% load static %}
<script src="{% static 'poems/anime.min.js' %}"></script>
<script>
var lenLemmedWords = {{len_lemmed_words}}
    anime({
  targets: '#len_lemmed_words',
  value: [0, lenLemmedWords],
  round: 1,
  easing: 'easeInOutExpo',
  delay: 2000
});

var lenUniqueWords = {{len_unique_words}}
    anime({
  targets: '#len_unique_words',
  value: [0, lenUniqueWords],
  round: 1,
  easing: 'easeInOutExpo',
  delay: 2000
});

</script>


{% endblock %}

poetry/analytics/templates/analytics/checkbox.html
{% extends 'poems/base.html' %}
{% block content %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<h4 class="wow zoomIn" style="text-align: center">{{poet}}</h4>

<h4 class="wow zoomIn" style="text-align: center">Toп-100 слов</h4>

<p style="text-align: center">Задайте параметры либо нажмите ТОП-100 без указания параметров</p>





<form method="post">
      {% csrf_token %}
    <div class="container-dict">
        <div class="wow fadeInLeft  data-wow-duration="2s"">
            <p style="background-color: rgba(0, 128, 128, 0.4); color: white"> {{form}}</p>
    </div>
    <br>
    <p><input type="submit" value="ТОП-100 СЛОВ"></p>

</form>


{% endblock %}

poetry/analytics/templates/analytics/poem_dictionary.html
{% extends 'poems/base.html' %}
{% block content %}



<div class="container-1">
    <div class="block-main box-flex wow fadeInUp  data-wow-duration="2s">
        <h3 style="text-align: center"><a href="{% url 'poems:poem_single' pk=poem_original.pk %}">{{poem_original.poem_title}}</a></h3>
        <p class="text-poem">{{poem_original.poem_text}}</p>
     </div>
</div>

<div class="wow fadeIn data-wow-duration="2s"">
<p style="text-align: center; text-transform: uppercase">Словарь стихотворения</p>
</div>

<div class="container-numbers">

    <div>
        <p>Всего слов</p>
        <p><input id="len_lemmed_words" value="0"></p>
    </div>
    <div>
        <p>Уникальных слов</p>
        <p><input id="len_unique_words" value="0"></p>
    </div>

</div>

    <div class="container-dict">
        {% for p, j in poem.items %}
            <div class="wow fadeInLeft  data-wow-duration="2s"">
                <p style="background-color: rgba(0, 128, 128, 0.4); color: white">{{p}}</p>
                {% for word in j %}
                {{word}}
                {% endfor %}
             </div>
        {% endfor %}
    </div>

<p><a href="{% url 'poems:audio' pk=pk %}" target="_blank">Аудио</a></p>


{% load static %}
<script src="{% static 'poems/anime.min.js' %}"></script>
<script>
var lenLemmedWords = {{len_lemmed_words}}
    anime({
  targets: '#len_lemmed_words',
  value: [0, lenLemmedWords],
  round: 1,
  easing: 'easeInOutExpo',
  delay: 2000
});

var lenUniqueWords = {{len_unique_words}}
    anime({
  targets: '#len_unique_words',
  value: [0, lenUniqueWords],
  round: 1,
  easing: 'easeInOutExpo',
  delay: 2000
});

</script>


{% endblock %}

poetry/analytics/templates/analytics/poet_analytics.html
{% extends 'poems/base.html' %}
{% block content %}

<h2 style="text-align: center">{{poet}}</h2>

<div class="container-numbers">
    <div>
        <p>Стихов</p>
        <p><input id="poems_all" value="0"></p>
    </div>
    <div>
        <p>Всего слов</p>
        <p><input id="counter_all" value="0"></p>
    </div>
    <div>
        <p>Уникальных слов</p>
        <p><input id="counter_unique" value="0"></p>
    </div>
</div>
<h3 style="text-align: center">Топ-100 слов:</h3>
<div class="words_counts">
<ol style="color: black">
    {% for i in result %}
       <li> <div class="words_counts_elements">
            {{i}}
        </div></li>
    {% endfor %}
</ol>
</div>
{% load static %}
<script src="{% static 'poems/anime.min.js' %}"></script>

<script>
var counterAll = {{counter_all}}
    anime({
  targets: '#counter_all',
  value: [0, counterAll],
  round: 1,
  easing: 'easeInOutExpo'
});
var counterUnique = {{counter_unique}}
    anime({
  targets: '#counter_unique',
  value: [0, counterUnique],
  round: 1,
  easing: 'easeInOutExpo'
});

var poemsAll = {{poems_all}}
    anime({
  targets: '#poems_all',
  value: [0, poemsAll],
  round: 1,
  easing: 'easeInOutExpo'
});
</script>



{% endblock %}

poetry/analytics/templates/analytics/top_100_adjf.html
{% extends 'poems/base.html' %}
{% block content %}


<div class="container-numbers">
    <div>
        <p>Стихов</p>
        <p><input id="poems_all" value="0"></p>
    </div>
    <div>
        <p>Всего слов</p>
        <p><input id="counter_all" value="0"></p>
    </div>
    <div>
        <p>Уникальных слов</p>
        <p><input id="counter_unique" value="0"></p>
    </div>
</div>
<h3 style="text-align: center">Топ-100 прилагательных:</h3>
<div class="words_counts">
<ol style="color: black">
    {% for i in result %}
       <li> <div class="words_counts_elements">
            {{i}}
        </div></li>
    {% endfor %}
</ol>
</div>
{% load static %}
<script src="{% static 'poems/anime.min.js' %}"></script>

<script>
var counterAll = {{counter_all}}
    anime({
  targets: '#counter_all',
  value: [0, counterAll],
  round: 1,
  easing: 'easeInOutExpo'
});
var counterUnique = {{counter_unique}}
    anime({
  targets: '#counter_unique',
  value: [0, counterUnique],
  round: 1,
  easing: 'easeInOutExpo'
});

var poemsAll = {{poems_all}}
    anime({
  targets: '#poems_all',
  value: [0, poemsAll],
  round: 1,
  easing: 'easeInOutExpo'
});
</script>



{% endblock %}

poetry/analytics/templates/analytics/top_100_nouns.html
{% extends 'poems/base.html' %}
{% block content %}


<div class="container-numbers">
    <div>
        <p>Стихов</p>
        <p><input id="poems_all" value="0"></p>
    </div>
    <div>
        <p>Всего слов</p>
        <p><input id="counter_all" value="0"></p>
    </div>
    <div>
        <p>Уникальных слов</p>
        <p><input id="counter_unique" value="0"></p>
    </div>
</div>
<h3 style="text-align: center">Топ-100 существительных</h3>
<div class="words_counts">
<ol style="color: black">
    {% for i in result %}
       <li> <div class="words_counts_elements">
            {{i}}
        </div></li>
    {% endfor %}
</ol>
</div>
{% load static %}
<script src="{% static 'poems/anime.min.js' %}"></script>

<script>
var counterAll = {{counter_all}}
    anime({
  targets: '#counter_all',
  value: [0, counterAll],
  round: 1,
  easing: 'easeInOutExpo'
});
var counterUnique = {{counter_unique}}
    anime({
  targets: '#counter_unique',
  value: [0, counterUnique],
  round: 1,
  easing: 'easeInOutExpo'
});

var poemsAll = {{poems_all}}
    anime({
  targets: '#poems_all',
  value: [0, poemsAll],
  round: 1,
  easing: 'easeInOutExpo'
});
</script>



{% endblock %}

poetry/analytics/templates/analytics/top_100_nouns_and_adjf.html
{% extends 'poems/base.html' %}
{% block content %}


<div class="container-numbers">
    <div>
        <p>Стихов</p>
        <p><input id="poems_all" value="0"></p>
    </div>
    <div>
        <p>Всего слов</p>
        <p><input id="counter_all" value="0"></p>
    </div>
    <div>
        <p>Уникальных слов</p>
        <p><input id="counter_unique" value="0"></p>
    </div>
</div>
<h3 style="text-align: center">Топ-100 существительных и прилагательных</h3>
<div class="words_counts">
<ol style="color: black">
    {% for i in result %}
       <li> <div class="words_counts_elements">
            {{i}}
        </div></li>
    {% endfor %}
</ol>
</div>
{% load static %}
<script src="{% static 'poems/anime.min.js' %}"></script>

<script>
var counterAll = {{counter_all}}
    anime({
  targets: '#counter_all',
  value: [0, counterAll],
  round: 1,
  easing: 'easeInOutExpo'
});
var counterUnique = {{counter_unique}}
    anime({
  targets: '#counter_unique',
  value: [0, counterUnique],
  round: 1,
  easing: 'easeInOutExpo'
});

var poemsAll = {{poems_all}}
    anime({
  targets: '#poems_all',
  value: [0, poemsAll],
  round: 1,
  easing: 'easeInOutExpo'
});
</script>



{% endblock %}

poetry/analytics/templates/analytics/top_100_nouns_and_verbs.html
{% extends 'poems/base.html' %}
{% block content %}


<div class="container-numbers">
    <div>
        <p>Стихов</p>
        <p><input id="poems_all" value="0"></p>
    </div>
    <div>
        <p>Всего слов</p>
        <p><input id="counter_all" value="0"></p>
    </div>
    <div>
        <p>Уникальных слов</p>
        <p><input id="counter_unique" value="0"></p>
    </div>
</div>
<h3 style="text-align: center">Топ-100 существительных и глаголов</h3>
<div class="words_counts">
<ol style="color: black">
    {% for i in result %}
       <li> <div class="words_counts_elements">
            {{i}}
        </div></li>
    {% endfor %}
</ol>
</div>
{% load static %}
<script src="{% static 'poems/anime.min.js' %}"></script>

<script>
var counterAll = {{counter_all}}
    anime({
  targets: '#counter_all',
  value: [0, counterAll],
  round: 1,
  easing: 'easeInOutExpo'
});
var counterUnique = {{counter_unique}}
    anime({
  targets: '#counter_unique',
  value: [0, counterUnique],
  round: 1,
  easing: 'easeInOutExpo'
});

var poemsAll = {{poems_all}}
    anime({
  targets: '#poems_all',
  value: [0, poemsAll],
  round: 1,
  easing: 'easeInOutExpo'
});
</script>



{% endblock %}

poetry/analytics/templates/analytics/top_100_nouns_and_verbs_and_adjf.html
{% extends 'poems/base.html' %}
{% block content %}


<div class="container-numbers">
    <div>
        <p>Стихов</p>
        <p><input id="poems_all" value="0"></p>
    </div>
    <div>
        <p>Всего слов</p>
        <p><input id="counter_all" value="0"></p>
    </div>
    <div>
        <p>Уникальных слов</p>
        <p><input id="counter_unique" value="0"></p>
    </div>
</div>
<h3 style="text-align: center">Топ-100 существительных, глаголов и прилагательных</h3>
<div class="words_counts">
<ol style="color: black">
    {% for i in result %}
       <li> <div class="words_counts_elements">
            {{i}}
        </div></li>
    {% endfor %}
</ol>
</div>
{% load static %}
<script src="{% static 'poems/anime.min.js' %}"></script>

<script>
var counterAll = {{counter_all}}
    anime({
  targets: '#counter_all',
  value: [0, counterAll],
  round: 1,
  easing: 'easeInOutExpo'
});
var counterUnique = {{counter_unique}}
    anime({
  targets: '#counter_unique',
  value: [0, counterUnique],
  round: 1,
  easing: 'easeInOutExpo'
});

var poemsAll = {{poems_all}}
    anime({
  targets: '#poems_all',
  value: [0, poemsAll],
  round: 1,
  easing: 'easeInOutExpo'
});
</script>



{% endblock %}

poetry/analytics/templates/analytics/top_100_verbs.html
{% extends 'poems/base.html' %}
{% block content %}


<div class="container-numbers">
    <div>
        <p>Стихов</p>
        <p><input id="poems_all" value="0"></p>
    </div>
    <div>
        <p>Всего слов</p>
        <p><input id="counter_all" value="0"></p>
    </div>
    <div>
        <p>Уникальных слов</p>
        <p><input id="counter_unique" value="0"></p>
    </div>
</div>
<h3 style="text-align: center">Топ-100 глаголов</h3>
<div class="words_counts">
<ol style="color: black">
    {% for i in result %}
       <li> <div class="words_counts_elements">
            {{i}}
        </div></li>
    {% endfor %}
</ol>
</div>
{% load static %}
<script src="{% static 'poems/anime.min.js' %}"></script>

<script>
var counterAll = {{counter_all}}
    anime({
  targets: '#counter_all',
  value: [0, counterAll],
  round: 1,
  easing: 'easeInOutExpo'
});
var counterUnique = {{counter_unique}}
    anime({
  targets: '#counter_unique',
  value: [0, counterUnique],
  round: 1,
  easing: 'easeInOutExpo'
});

var poemsAll = {{poems_all}}
    anime({
  targets: '#poems_all',
  value: [0, poemsAll],
  round: 1,
  easing: 'easeInOutExpo'
});
</script>



{% endblock %}

poetry/analytics/templates/analytics/top_100_verbs_and_adjf.html
{% extends 'poems/base.html' %}
{% block content %}


<div class="container-numbers">
    <div>
        <p>Стихов</p>
        <p><input id="poems_all" value="0"></p>
    </div>
    <div>
        <p>Всего слов</p>
        <p><input id="counter_all" value="0"></p>
    </div>
    <div>
        <p>Уникальных слов</p>
        <p><input id="counter_unique" value="0"></p>
    </div>
</div>
<h3 style="text-align: center">Топ-100 глаголов и прилагательных</h3>
<div class="words_counts">
<ol style="color: black">
    {% for i in result %}
       <li> <div class="words_counts_elements">
            {{i}}
        </div></li>
    {% endfor %}
</ol>
</div>
{% load static %}
<script src="{% static 'poems/anime.min.js' %}"></script>

<script>
var counterAll = {{counter_all}}
    anime({
  targets: '#counter_all',
  value: [0, counterAll],
  round: 1,
  easing: 'easeInOutExpo'
});
var counterUnique = {{counter_unique}}
    anime({
  targets: '#counter_unique',
  value: [0, counterUnique],
  round: 1,
  easing: 'easeInOutExpo'
});

var poemsAll = {{poems_all}}
    anime({
  targets: '#poems_all',
  value: [0, poemsAll],
  round: 1,
  easing: 'easeInOutExpo'
});
</script>



{% endblock %}