poetry/analytics/urls.py
from django.urls import path
from . import views

app_name = 'analytics'

urlpatterns = [
    path('options/<poet>/', views.checkbox_dictionary, name='analytics_main'),
    path('dictionary/<int:pk>/', views.poem_dictionary, name='pd'),
    path('all_words_counted/<poet>/', views.all_words_counted, name='all_words_counted'),
    path('top_100_nouns/<poet>/', views.top_100_nouns, name='top_100_nouns'),
    path('top_100_adjf/<poet>/', views.top_100_adjf, name='top_100_adjf'),
    path('top_100_nouns_and_adjf/<poet>/', views.top_100_nouns_and_adjf, name='top_100_nouns_and_adjf'),
    path('top_100_verbs/<poet>/', views.top_100_verbs, name='top_100_verbs'),
    path('top_100_nouns_and_verbs/<poet>/', views.top_100_nouns_and_verbs, name='top_100_nouns_and_verbs'),
    path('top_100_nouns_and_verbs_and_adjf/<poet>/', views.top_100_nouns_and_verbs_and_adjf, name='top_100_nouns_and_verbs_and_adjf'),
    path('top_100_verbs_and_adjf/<poet>/', views.top_100_verbs_and_adjf, name='top_100_verbs_and_adjf'),


]

poetry/poems/urls.py
from django.urls import path
from . import views


app_name = 'poems'

urlpatterns = [
    path('poet/<poet>', views.poems_author, name='poems_author'),
    path('contents/<poet>', views.contents_author, name='contents_author'),
    path('add/', views.poem_add, name='poem_add'),
    path('poem_single/<int:pk>/', views.PoemDetailView.as_view(), name='poem_single'),
    path('delete/<int:pk>/', views.PoemDeleteView.as_view(), name='poem_delete'),
    path('contents/', views.ContentsView.as_view(), name='contents'),
    path('audio/<int:pk>/', views.audio_poem, name='audio'),
    path('update/<int:pk>/', views.PoemUpdateView.as_view(), name='poem_update'),
]

poetry/poetry/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


from rest_framework import routers
from poems.api_views import TagViewSet, EmelyanovaPoemViewSet



# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register('tag', TagViewSet)
router.register('emelyanova', EmelyanovaPoemViewSet)








from users.models import CustomAuthToken


urlpatterns = [
    path('admin/', admin.site.urls),
    path('poems/', include('poems.urls')),
    path('users/', include('users.urls')),
    path('analytics/', include('analytics.urls')),
    path('', views.home_page, name ='home'),
    path('api/v0/', include(router.urls)),
    path('api_token/', CustomAuthToken.as_view())


]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
'''
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns
'''

# from rest_framework.authtoken import views
#
# urlpatterns += [
#     path('api_token/', views.obtain_auth_token)
# ]

poetry/users/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth.views import LogoutView


app_name = 'users'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name = 'login'),
    path('register/', views.UserCreateView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('token_options/', views.get_token, name='token_options'),
    path('get_token/', views.get_token, name='get_token'),
    path('update_token/', views.update_token, name='update_token'),

]

poetry/poems/models.py
import re
from django.db import models
from analytics.PoetAnalytics import MetaPoet
from django.utils.functional import cached_property
from django.dispatch import receiver
from django.db.models.signals import post_save

class IsActiveMixin(models.Model):
    is_active = models.BooleanField(default=True)
    class Meta:
        abstract = True

class MainPoetManager(models.Manager):
    def get_queryset(self):
        all_objects = super().get_queryset()
        return all_objects.filter(poet_name__custom_id=1, is_active=True)

class Tag(IsActiveMixin, models.Model):
    tag_name = models.CharField(max_length=100, default="n/a")

    def __str__(self):
        return f'{self.tag_name}'

class Poet(IsActiveMixin, models.Model):
    poets = models.Manager()
    custom_id = models.IntegerField(null=True)
    last_name = models.CharField(max_length=100, default='n/a', db_index=True)
    first_name = models.CharField(max_length=100, default='n/a')
    father_name = models.CharField(max_length=100, null=True, blank=True, default='' )
    poet_img = models.ImageField(upload_to='poems', null=True, blank=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'




class Poem(IsActiveMixin, models.Model):
    poem_text = models.TextField()
    poem_title = models.CharField(max_length=200)
    poem_year = models.CharField(max_length=10,null=True, blank=True)
    first_line = models.CharField(max_length=200, null=True, blank=True)
    poem_tag = models.ManyToManyField(Tag, blank=True)
    poet_name = models.ForeignKey(Poet, on_delete=models.CASCADE, default=1)
    poem_audio = models.FileField(upload_to='poems/audio', null=True, blank=True)
    poem_img = models.ImageField(upload_to='poems', null=True, blank=True)

    objects = models.Manager()
    emelyanova = MainPoetManager()


    class Meta:
        ordering = ['-id']




    def __str__(self):
        return f'{self.poem_title}'

#5 количество слов в стихе
    def len_poem_text(self):
        self.words = MetaPoet(str(self.poem_text))
        self.words.remove_punctuation()
        self.words.split_words()
        return len(self.words)

    def poem_words(self):
        self.words = MetaPoet(str(self.poem_text))
        self.words.remove_punctuation()
        self.words.split_words()
        return self.words


#_____Функция для тестсирования
#1 количество тэгов у стиха
@cached_property
def get_all_tags(self):
    return Tag.objects.all()

#2 есть ли у объекта теги
def tag_is(self):
    if len(self.poem_tag.all()) == 0:
        return False
    return True

#3 Если у стиха в названии "* * *", возвращает noname
def poem_no_name(self):
    if self.poem_title == '* * *':
        return 1
    return 2
#4 заполнено ли поле "первая строка"
def first_line_is(self):
    if self.first_line == None:
        return False
    return True



# вариант сигнала - сохранение первой строки в поле 'firstline' для отображения в содержании
# class Firstline(models.Model):
#     first_line_signal = models.CharField(max_length=200, null=True, blank=True)
#     poem = models.OneToOneField(Poem, on_delete=models.CASCADE, primary_key=True)
#
#     def __str__(self):
#         return f'{self.first_line_signal}'


#
#
# @receiver(post_save, sender=Poem)
# def create_first_line(sender, instance, **kwargs):
#     text = instance.poem_text
#     str_add = text.split('\n')[0]
#     # instance.first_line = str_add
#     # instance.save()
#     Firstline.objects.create(poem=instance, first_line_signal=str_add)

poetry/poems/forms.py
from django import forms
from .models import Poem

class PoemForm(forms.ModelForm):
    poem_title = forms.CharField(label = 'Название')


    class Meta:
        model = Poem
        # fields = '__all__'
        exclude = ['poem_audio','poem_img']

poetry/poems/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
# Create your views here.
from .models import Poem, Poet
from .forms import PoemForm
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .AudioPoet import AudioPoet
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger




# все стихи всех поэтов
class PoemView(ListView):
    model = Poem
    template_name = 'poems/poems.html'
    context_object_name = 'poem'
    paginate_by = 10

# стихи одного автора

def poems_author(request, poet):
    poem = Poem.objects.prefetch_related('poem_tag').filter(poet_name__last_name=poet).filter(is_active=True)
    paginator = Paginator(poem, 15)  # Show 15 contacts per page.
    page = request.GET.get('page')
    try:
        poem = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        poem = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        poem = paginator.page(paginator.num_pages)

    return render(request, 'poems/poems_author.html', {'poem': poem, 'p_':poem[0]})



class ContentsView(ListView):
    model = Poem
    template_name = 'poems/contents.html'
    context_object_name = 'poem'

    def get_queryset(self):
        return Poem.objects.filter(is_active=True)

# содержание по одному автору

def contents_author(request, poet):
    poem = Poem.objects.filter(poet_name__last_name=poet)
    return render(request, 'poems/contents_author.html', {'poem':poem})


class PoemUpdateView(UpdateView):
    model = Poem
    template_name = 'poems/poem_update.html'
    fields = ['is_active','poem_title', 'poem_text', 'poem_year', 'first_line', 'poem_tag', 'poet_name']
    success_url = reverse_lazy('home')


@user_passes_test(lambda user: user.is_superuser)
def poem_add(request):
    if request.method == "GET":
        form = PoemForm
        return render(request, 'poems/poem_add.html', {'form': form})
    else:
        form = PoemForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('home'))
        else:
            return render(request, 'poems/poem_add.html', {'form': form})

class PoemDetailView(DetailView):
    model = Poem
    template_name = 'poems/poem_single.html'

class PoemDeleteView(UserPassesTestMixin, DeleteView):

    template_name = 'poems/poem_delete.html'
    model = Poem
    success_url = reverse_lazy('home')

    def test_func(self):
        return self.request.user.is_superuser

    def handle_no_permission(self):
        return HttpResponseRedirect(reverse('home'))

def audio_poem(request, pk):

    poem = get_object_or_404(Poem, pk=pk)
    text = str(poem.poem_text)
    a = AudioPoet(text)
    a.audio()
    poem.poem_audio = 'poems/audio/1.mp3'
    poem.save()

    return render(request, 'poems/poem_audio.html', {'poem': poem})

poetry/poems/templates/poems/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="keywords" content="стихи, литература">
    <meta name="description" content="Стихи.">
    <title>Poems</title>
    {% load static %}
    <link rel="stylesheet" href='{% static "poems/style.css" %}'>
    <link rel="stylesheet" href='{% static "poems/style-menu.css" %}'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href='{% static "poems/animate.css" %}'>
    <link rel="stylesheet" href='{% static "poems/flex.css" %}'>
</head>

<style>
html,
body {
  height: 100%;
}
#wrap {
  min-height: 100%;
}
main {
  padding-bottom: 100px;
  /*Высота футера*/
}
footer {
  margin-top: -100px;
  /*Минус Высота футера*/
  height: 100px;
  /*Высота футера*/
}
</style>
<div id="wrap">
<body class="light-theme">

<header>

    <div class="burger-menu">
        <a href="#" class="burger-menu__button">
            <span class="burger-menu__lines"></span>
        </a>

        <nav class="burger-menu__nav">
            <span  style="text-align: center">
                <button type="submit" class="btn-01 btn-light wow jackInTheBox">DARK/LIGHT MODE</button>
            </span>
            <a class="burger-menu__link" href="{% url 'home' %}">&cir; Home</a>
            <a class="burger-menu__link" href="/api/v0/">&EmptySmallSquare; API</a>
            {% if user.is_authenticated %}
            <a class="burger-menu__link" href="{% url 'users:get_token' %}">&#9872; Token</a>
            {% endif %}

            {% if user.is_superuser %}
            <a class="burger-menu__link" href="{% url 'poems:poem_add' %}">&#10052; Add</a>
            {% endif %}
                {% if user.is_authenticated %}
            <p class="auth_phrase">Рады приветствовать, <br>{{user.username}}</p>
            <a class="burger-menu__link" href="{% url 'users:logout' %}">&#10006; Exit</a>
                {% else %}
            <a class="burger-menu__link" href="{% url 'users:login' %}">&#9786; Auth</a>
            <a class="burger-menu__link" href="{% url 'users:register' %}">&#10086; Register</a>
            {% endif %}

        </nav>

        <div class="burger-menu__overlay"></div>

</div>

<span>
    <h3 class="wow zoomIn" style="text-align: center; padding-top: 50px;">MetaPoet</h3>
    <h4 class="wow zoomIn" style="text-align: center">Clara Emelyanova</h4>


</span>

</header>

<main>
{% block content %}{% endblock %}
</main>
</div>
<footer>
    <div class="footer-class">
        <p>&#10026; Developed by <a href="https://github.com/tahoeivanova">Tahoe Ivanova</a></p>
    </div>
</footer>
<script src="{% static 'poems/script.js' %}"></script>
<script src="{% static 'poems/animation-text.js' %}"></script>
<script src="https://js.cx/libs/animate.js"></script>

<script src="{% static 'poems/wow.min.js' %}"></script>
<script src="{% static 'poems/archimed-spiral.js' %}"></script>

<script src="http://code.jquery.com/jquery-1.8.3.js"></script>
<script src="{% static 'poems/script-menu.js' %}"></script>


<script>
    new WOW().init();
</script>
</body>
</html>

poetry/poems/templates/poems/contents_author.html
{% extends 'poems/base.html'%}
{% block content %}

<style>
#myInput {

	width: 100%;
	font-size: 16px;
	padding: 12px 20px 12px 5px;
	border: 1px solid #ddd;
	margin-bottom: 12px;
}

#myUl {

	list-style: none;
	padding: 0;
	margin: 0;
}

#myUl li a {
	border: 1px solid #ddd;
	margin-top: -1px;
	background-color: #f6f6f6;
	padding: 12px;
	text-decoration: none;
	font-size: 18px;
	color: black;
	display: block;
}

#myUl li a.header {
	background-color: #e2e2e2;
	cursor: default;
}
#myUl li a:hover {
		background-color: #eee;

}
</style>

<input type="text" onkeyup="myFunction()" id="myInput" placeholder="Search for names">



    <ul id="myUl">
    {% for i in poem %}

        {% if i.first_line == None %}
        <li><a href="{% url 'analytics:pd' pk=i.pk %}">{{i.poem_title}}</a></li>
<!--        <li><a href="{% url 'analytics:pd' pk=i.pk %}">{{i.poem_title}} ({{i.firstline}})</a></li>-->
        {% else %}
        <li><a href="{% url 'analytics:pd' pk=i.pk %}">{{i.poem_title}} ({{i.first_line}})</a></li>
        {% endif %}
        {% endfor %}
 	</ul>

<script>

    function myFunction() {
	var input, filter, ul, li, a, i;
	input = document.getElementById("myInput");
	filter = input.value.toUpperCase();
	ul = document.getElementById("myUl");
	li = ul.getElementsByTagName("li");

	for (i=0; i<li.length; i++) {
		a = li[i].getElementsByTagName("a")[0]
		if (a.innerHTML.toUpperCase().indexOf(filter)>-1) {
			li[i].style.display = "";
		} else {
			li[i].style.display = "none"
		}
	}

}
</script>

{% endblock %}

poetry/poems/templates/poems/index.html
{% extends 'poems/base.html' %}
{% block content %}
  <div style="text-align: center; padding-bottom: 50px;">
        <a href="{% url 'home' %}">
        <canvas class="wow rotateIn" data-wow-duration="2s" id="spiralCanvas" width="300" height="300"></canvas>
        </a>
    </div>

<div style="text-align: center">
        <div style="text-align: center" class="wow fadeInLeft  data-wow-duration="2s">



            <h4><a href="{% url 'poems:poems_author' poet=poet.last_name%}">Стихи</a></h4>
            <h4><a  href="{% url 'poems:contents_author' poet=poet.last_name%}">Содержание</a></h4>
            <h4><a  href="{% url 'analytics:analytics_main' poet=poet.last_name%}" target="_blank">Аналитика</a></h4>



        </div>

</div>



{% endblock %}

poetry/poems/templates/poems/poem_add.html
{% extends 'poems/base.html'%}
{% block content %}
<div>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button style="margin-left: 10px" type="submit">Добавить</button>
    </form>
</div>
{% endblock %}

poetry/poems/templates/poems/poem_audio.html
{% extends 'poems/base.html'%}
{% block content %}
<header>
</header>

    {% load static %}
<div style="margin: 10px; text-align: center">
    <h3 style="margin-bottom: 10px">{{poem.poem_title}}</h3>

    <audio  controls preload="auto">
        <source src="{{poem.poem_audio.url}}" type="audio/mpeg">
        <source src="{{poem.poem_audio.url}}" type="audio/ogg">
        Ваш браузер не поддерживает тег audio ОБНОВИТЕ БРАУЗЕР!
    </audio>
    </br>
    {% if poem.poem_img %}
    <img src="{{poem.poem_img.url}}" height='300' alt="{{poem.title}}">
    {% endif %}
    <pre>{{poem.poem_text}}</pre>


</div>

{% endblock %}

poetry/poems/templates/poems/poem_delete.html
{% extends 'poems/base.html'%}
{% block content %}
<section style="margin: 10px;">

    <p>{{object.poem_title}}</p>
    <p>Вы уверены</p>
        <form method="POST">
        {% csrf_token %}
        <button type="submit">Да</button>

        </form>
</section>
{% endblock %}

poetry/poems/templates/poems/poem_single.html
{% extends 'poems/base.html'%}
{% block content %}
<header>
</header>

<div style="margin-left:10px">
    <h3 class="text-title"><a href="{% url 'analytics:pd' pk=object.pk%}">{{object.poem_title}}</a></h3>
    <textarea class="text" id="textExample" rows="10" cols="60">{{object.poem_text}}</textarea>
    <button onclick="animateText(textExample)" class="btn-light btn btn-send-message btn-md" type="submit">Запустить анимацию набора текста!</button>

</div>
<p>Количество тэгов: {{object.tag_number}}</p>
<div>
    <p>Тэги:</p>
    <ul>
        {% for i in object.poem_tag.all %}
        <li>{{i}}</li>
        {%endfor%}
    </ul>
</div>
<p><a href="{% url 'poems:audio' pk=object.pk %}">Аудио</a></p>

<p><a href="{% url 'analytics:pd' pk=object.pk %}">Словарь стихотворения</a></p>

{% if user.is_superuser %}
    <p><a href="{% url 'poems:poem_update' pk=object.pk %}">Изменить</a></p>
    <p><a href="{% url 'poems:poem_delete' pk=object.pk %}">Удалить</a></p>
    <p
    ><a href="{% url 'poems:poem_add' %}" target="_blank">Добавить стих</a></p>
{% endif %}
{% endblock %}

poetry/poems/templates/poems/poem_update.html
{% extends 'poems/base.html'%}
{% block content %}
<section>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
    </form>

</section>
{% endblock %}

poetry/poems/templates/poems/poems.html
{% extends 'poems/base.html'%}
{% block content %}


<header>

</header>
        <div class="container-1">
        {% for p in poem %}
            <div class="block-main box-flex wow fadeInUp  data-wow-duration="2s">
                <h3 style="text-align: center"><a href="{% url 'poems:poem_single' pk=p.pk %}">{{p.poem_title}}</a></h3>
                <p class="text-poem">{{p.poem_text}}</p>
                <p>{{p.poem_year}}</p>
                <p>{{p.poet_name}}</p>
                {% if user.is_superuser %}
                <p><a href="{% url 'poems:poem_update' pk=p.pk %}">Изменить</a></p>
                <p><a href="{% url 'poems:poem_delete' pk=p.pk %}">Удалить</a></p>
                <p><a href="{% url 'poems:poem_add' %}">Добавить стих</a></p>
                {% endif %}
                <p><a href="{% url 'poems:audio' pk=p.pk %}">Аудио</a></p>
                <p><a href="{% url 'analytics:pd' pk=p.pk %}">Словарь стихотворения</a></p>

             </div>
        {% endfor %}
        </div>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>




{% endblock %}

poetry/poems/templates/poems/poems_author.html
{% extends 'poems/base.html'%}
{% block content %}


<header>

</header>

        <div class="container-1">
        {% with poet_=p_.poet_name %}
        {% for p in poem %}

            <div class="block-main box-flex wow fadeInUp  data-wow-duration="2s">
                <h3 style="text-align: center"><a href="{% url 'analytics:pd' pk=p.pk %}">{{p.poem_title}}</a></h3>
                <p class="text-poem" style="text-align: center">{{p.poem_text}}</p>
            {% if p.poem_img %}
<!--            <p style="text-align: center"><img src="{{p.poem_img.url}}" height='250' alt="{{p.poem_title}}">-->
<!--            </p>-->
                {% endif %}
                <p>{{poet_}}</p>
            {% if p.poem_year %}
                <p>{{p.poem_year}}</p>
            {% endif %}
                <p> Слов в стихе: {{p.poem_words | length}}</p>
                <p>{% for tag in p.poem_tag.all %}
            {{tag}}
                    {% endfor %}</p>



                {% if user.is_superuser %}
                <p style="text-align: right"><a href="{% url 'poems:poem_update' pk=p.pk %}">Изменить</a></p>
                <p style="text-align: right"><a href="{% url 'poems:poem_delete' pk=p.pk %}">Удалить</a></p>
<!--                <p style="text-align: right"><a href="{% url 'poems:poem_add' %}" target="_blank">Добавить стих</a></p>-->
                {% endif %}
                <p style="text-align: right"><a href="{% url 'poems:audio' pk=p.pk %}" target="_blank">Аудио</a></p>
                <p style="text-align: right"><a href="{% url 'analytics:pd' pk=p.pk %}" target="_blank">Словарь стихотворения</a></p>

             </div>
        {% endfor %}
        {% endwith %}
        </div>


   <div class="pagination">
    <span class="step-links">
        {% if poem.has_previous %}
            <a href="?page={{ poem.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ poem.number }} of {{ poem.paginator.num_pages }}.
        </span>

        {% if poem.has_next %}
            <a href="?page={{ poem.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>




{% endblock %}